//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Restaurant.Common.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our restaurant strives to source local, sustainable and organic at all times. We work hard to source premium ingredients and we cook everything from scratch with love..
        /// </summary>
        public static string ABOUT_OUR_MISSION {
            get {
                return ResourceManager.GetString("ABOUT_OUR_MISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We also do our best to pay our employees living wages (tips are shared with all employees, including kitchen staff) and to reduce our environmental footprint wherever we can..
        /// </summary>
        public static string ABOUT_OUR_POLICY_FIRST {
            get {
                return ResourceManager.GetString("ABOUT_OUR_POLICY_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overall, these factors translate to higher menu prices, but we hope that you find value and feel a sense of comfort in knowing that we aim to get better everyday at doing what is important to us..
        /// </summary>
        public static string ABOUT_OUR_POLICY_SECOND {
            get {
                return ResourceManager.GetString("ABOUT_OUR_POLICY_SECOND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string ABOUT_US {
            get {
                return ResourceManager.GetString("ABOUT_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        public static string ACCEPT {
            get {
                return ResourceManager.GetString("ACCEPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string ACCOUNT {
            get {
                return ResourceManager.GetString("ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add a new address.
        /// </summary>
        public static string ADD_NEW_ADDRESS {
            get {
                return ResourceManager.GetString("ADD_NEW_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add review.
        /// </summary>
        public static string ADD_REVIEW {
            get {
                return ResourceManager.GetString("ADD_REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        public static string ADD_TO_CART {
            get {
                return ResourceManager.GetString("ADD_TO_CART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string ADDRESS {
            get {
                return ResourceManager.GetString("ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address name.
        /// </summary>
        public static string ADDRESS_NAME {
            get {
                return ResourceManager.GetString("ADDRESS_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address line two.
        /// </summary>
        public static string ADR_LINE_2 {
            get {
                return ResourceManager.GetString("ADR_LINE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All rights reserved.
        /// </summary>
        public static string ALL_RIGHTS_RESERVED {
            get {
                return ResourceManager.GetString("ALL_RIGHTS_RESERVED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string ARE_YOU_SURE {
            get {
                return ResourceManager.GetString("ARE_YOU_SURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BACK {
            get {
                return ResourceManager.GetString("BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best way to share your feedback is by.
        /// </summary>
        public static string BEST_WAY_TO {
            get {
                return ResourceManager.GetString("BEST_WAY_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book now.
        /// </summary>
        public static string BOOK_NOW {
            get {
                return ResourceManager.GetString("BOOK_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book a table.
        /// </summary>
        public static string BOOK_TABLE {
            get {
                return ResourceManager.GetString("BOOK_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        public static string BOOKING {
            get {
                return ResourceManager.GetString("BOOKING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can&apos;t seem to find what you&apos;re looking for..
        /// </summary>
        public static string CAN_T_FIND_CONTENT {
            get {
                return ResourceManager.GetString("CAN\'T_FIND_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string CART {
            get {
                return ResourceManager.GetString("CART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart summary.
        /// </summary>
        public static string CART_SUMMARY {
            get {
                return ResourceManager.GetString("CART_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string CHECKOUT {
            get {
                return ResourceManager.GetString("CHECKOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a delivery address.
        /// </summary>
        public static string CHOOSE_ADDRESS {
            get {
                return ResourceManager.GetString("CHOOSE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a category.
        /// </summary>
        public static string CHOOSE_CATEGORY {
            get {
                return ResourceManager.GetString("CHOOSE_CATEGORY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a date.
        /// </summary>
        public static string CHOOSE_DATE {
            get {
                return ResourceManager.GetString("CHOOSE_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a time.
        /// </summary>
        public static string CHOOSE_TIME {
            get {
                return ResourceManager.GetString("CHOOSE_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CITY {
            get {
                return ResourceManager.GetString("CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CLOSE {
            get {
                return ResourceManager.GetString("CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        public static string COMPANY {
            get {
                return ResourceManager.GetString("COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ul. &quot;Han Asparuh&quot; 37, 1000 Sofia Center, Sofia..
        /// </summary>
        public static string COMPANY_ADDRESS {
            get {
                return ResourceManager.GetString("COMPANY_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed on.
        /// </summary>
        public static string COMPLETED_ON {
            get {
                return ResourceManager.GetString("COMPLETED_ON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to contact us.
        /// </summary>
        public static string CONTACT_US {
            get {
                return ResourceManager.GetString("CONTACT_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string CONTACTS {
            get {
                return ResourceManager.GetString("CONTACTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string COUNTRY {
            get {
                return ResourceManager.GetString("COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer feedback.
        /// </summary>
        public static string CUSTOMER_FEEDBACK {
            get {
                return ResourceManager.GetString("CUSTOMER_FEEDBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date booked.
        /// </summary>
        public static string DATE_BOOKED {
            get {
                return ResourceManager.GetString("DATE_BOOKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery address.
        /// </summary>
        public static string DELIVERY_ADDRESS {
            get {
                return ResourceManager.GetString("DELIVERY_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery hours.
        /// </summary>
        public static string DELIVERY_HOURS {
            get {
                return ResourceManager.GetString("DELIVERY_HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DESCRIPTION {
            get {
                return ResourceManager.GetString("DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dishes.
        /// </summary>
        public static string DISHES {
            get {
                return ResourceManager.GetString("DISHES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string DISTRICT {
            get {
                return ResourceManager.GetString("DISTRICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To edit or cancel.
        /// </summary>
        public static string EDIT_OR_CANCEL {
            get {
                return ResourceManager.GetString("EDIT_OR_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimated delivery time.
        /// </summary>
        public static string EDT {
            get {
                return ResourceManager.GetString("EDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EMAIL {
            get {
                return ResourceManager.GetString("EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excellence.
        /// </summary>
        public static string EXCELLENCE {
            get {
                return ResourceManager.GetString("EXCELLENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experienced Chefs.
        /// </summary>
        public static string EXPERIENCED_CHEFS {
            get {
                return ResourceManager.GetString("EXPERIENCED_CHEFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of our employees have 20+ years of experince in the finest restaurants..
        /// </summary>
        public static string EXPERIENCED_CHEFS_DESC {
            get {
                return ResourceManager.GetString("EXPERIENCED_CHEFS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Delivery.
        /// </summary>
        public static string FAST_DELIVERY {
            get {
                return ResourceManager.GetString("FAST_DELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moneyback guarantee if you don&apos;t receive you order within 60 minutes..
        /// </summary>
        public static string FAST_DELIVERY_DESC {
            get {
                return ResourceManager.GetString("FAST_DELIVERY_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FIRST_NAME {
            get {
                return ResourceManager.GetString("FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five.
        /// </summary>
        public static string FIVE {
            get {
                return ResourceManager.GetString("FIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four.
        /// </summary>
        public static string FOUR {
            get {
                return ResourceManager.GetString("FOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front office.
        /// </summary>
        public static string FRONT_OFFICE {
            get {
                return ResourceManager.GetString("FRONT_OFFICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string GENERAL {
            get {
                return ResourceManager.GetString("GENERAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gourmet Experience.
        /// </summary>
        public static string GOURMET_EXPERIENCE {
            get {
                return ResourceManager.GetString("GOURMET_EXPERIENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string HOME {
            get {
                return ResourceManager.GetString("HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From juicy burgers to mouth-watering pizza - we&apos;ve got it all. All made using only the freshest ingredients from local markets..
        /// </summary>
        public static string HOME_PAGE_DESCRIPTION {
            get {
                return ResourceManager.GetString("HOME_PAGE_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hungry?.
        /// </summary>
        public static string HUNGRY {
            get {
                return ResourceManager.GetString("HUNGRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incredible.
        /// </summary>
        public static string INCREDIBLE {
            get {
                return ResourceManager.GetString("INCREDIBLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item total.
        /// </summary>
        public static string ITEM_TOTAL {
            get {
                return ResourceManager.GetString("ITEM_TOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LAST_NAME {
            get {
                return ResourceManager.GetString("LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LEARN_MORE {
            get {
                return ResourceManager.GetString("LEARN_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave a review.
        /// </summary>
        public static string LEAVE_REVIEW {
            get {
                return ResourceManager.GetString("LEAVE_REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to leaving a review!.
        /// </summary>
        public static string LEAVING_A_REVIEW {
            get {
                return ResourceManager.GetString("LEAVING_A_REVIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LOGIN {
            get {
                return ResourceManager.GetString("LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LOGOUT {
            get {
                return ResourceManager.GetString("LOGOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark this as my primary address.
        /// </summary>
        public static string MARK_PRIMARY_ADDRESS {
            get {
                return ResourceManager.GetString("MARK_PRIMARY_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Master Chefs.
        /// </summary>
        public static string MASTER_CHEFS {
            get {
                return ResourceManager.GetString("MASTER_CHEFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string MENU {
            get {
                return ResourceManager.GetString("MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully added the item to your cart!.
        /// </summary>
        public static string MODAL_SUCCESS_MESSAGE {
            get {
                return ResourceManager.GetString("MODAL_SUCCESS_MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday - Sunday.
        /// </summary>
        public static string MONDAY_TO_SUNDAY {
            get {
                return ResourceManager.GetString("MONDAY_TO_SUNDAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My reservations.
        /// </summary>
        public static string MY_RESERVATIONS {
            get {
                return ResourceManager.GetString("MY_RESERVATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string NEXT {
            get {
                return ResourceManager.GetString("NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m afraid you don&apos;t have any addresses added yet..
        /// </summary>
        public static string NO_ADDRESSES_YET {
            get {
                return ResourceManager.GetString("NO_ADDRESSES_YET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of people.
        /// </summary>
        public static string NUMBER_OF_PEOPLE {
            get {
                return ResourceManager.GetString("NUMBER_OF_PEOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh no!.
        /// </summary>
        public static string OH_NO {
            get {
                return ResourceManager.GetString("OH_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online Orders.
        /// </summary>
        public static string ONLINE_ORDERS {
            get {
                return ResourceManager.GetString("ONLINE_ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks to our logistics team you can enjoy our meals from the comfort of your home..
        /// </summary>
        public static string ONLINE_ORDERS_DESC {
            get {
                return ResourceManager.GetString("ONLINE_ORDERS_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops....
        /// </summary>
        public static string OPS {
            get {
                return ResourceManager.GetString("OPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string ORDER {
            get {
                return ResourceManager.GetString("ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order details.
        /// </summary>
        public static string ORDER_DETAILS {
            get {
                return ResourceManager.GetString("ORDER_DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number.
        /// </summary>
        public static string ORDER_NUMBER {
            get {
                return ResourceManager.GetString("ORDER_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay on delivery.
        /// </summary>
        public static string PAY_ON_DELIVERY {
            get {
                return ResourceManager.GetString("PAY_ON_DELIVERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        public static string PAYMENT {
            get {
                return ResourceManager.GetString("PAYMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        public static string PAYPAL {
            get {
                return ResourceManager.GetString("PAYPAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string PEOPLE {
            get {
                return ResourceManager.GetString("PEOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PHONE_NUMBER {
            get {
                return ResourceManager.GetString("PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place order.
        /// </summary>
        public static string PLACE_ORDER {
            get {
                return ResourceManager.GetString("PLACE_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please.
        /// </summary>
        public static string PLEASE {
            get {
                return ResourceManager.GetString("PLEASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string PREVIOUS {
            get {
                return ResourceManager.GetString("PREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string PRICE {
            get {
                return ResourceManager.GetString("PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy policy.
        /// </summary>
        public static string PRIVACY_POLICY {
            get {
                return ResourceManager.GetString("PRIVACY_POLICY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to proceed with your order..
        /// </summary>
        public static string PROCEED {
            get {
                return ResourceManager.GetString("PROCEED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed to checkout.
        /// </summary>
        public static string PROCEED_TO_CHECKOUT {
            get {
                return ResourceManager.GetString("PROCEED_TO_CHECKOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string PRODUCTS {
            get {
                return ResourceManager.GetString("PRODUCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Food.
        /// </summary>
        public static string QUALITY_FOOD {
            get {
                return ResourceManager.GetString("QUALITY_FOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use only the best ingredients from local markets. An incredible gourmet experience everytime..
        /// </summary>
        public static string QUALITY_FOOD_DESC {
            get {
                return ResourceManager.GetString("QUALITY_FOOD_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string QUANTITY {
            get {
                return ResourceManager.GetString("QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate our service.
        /// </summary>
        public static string RATE_OUR_SERVICE {
            get {
                return ResourceManager.GetString("RATE_OUR_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string REGISTER {
            get {
                return ResourceManager.GetString("REGISTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string REMOVE {
            get {
                return ResourceManager.GetString("REMOVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string RESERVATION {
            get {
                return ResourceManager.GetString("RESERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation number.
        /// </summary>
        public static string RESERVATION_NUMBER {
            get {
                return ResourceManager.GetString("RESERVATION_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share your feedback, recommendations, etc..
        /// </summary>
        public static string REVIEW_DESCRIPTION {
            get {
                return ResourceManager.GetString("REVIEW_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer reviews.
        /// </summary>
        public static string REVIEWS {
            get {
                return ResourceManager.GetString("REVIEWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve come to the right place!.
        /// </summary>
        public static string RIGHT_PLACE {
            get {
                return ResourceManager.GetString("RIGHT_PLACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SEND {
            get {
                return ResourceManager.GetString("SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping.
        /// </summary>
        public static string SHIPPING {
            get {
                return ResourceManager.GetString("SHIPPING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give us a short summary of your experience..
        /// </summary>
        public static string SHORT_SUMMARY {
            get {
                return ResourceManager.GetString("SHORT_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six.
        /// </summary>
        public static string SIX {
            get {
                return ResourceManager.GetString("SIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special request.
        /// </summary>
        public static string SPECIAL_REQUEST {
            get {
                return ResourceManager.GetString("SPECIAL_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string STREET {
            get {
                return ResourceManager.GetString("STREET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string SUBJECT {
            get {
                return ResourceManager.GetString("SUBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string SUBTOTAL {
            get {
                return ResourceManager.GetString("SUBTOTAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string SUCCESS {
            get {
                return ResourceManager.GetString("SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table for.
        /// </summary>
        public static string TABLE_FOR {
            get {
                return ResourceManager.GetString("TABLE FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table number.
        /// </summary>
        public static string TABLE_NUMBER {
            get {
                return ResourceManager.GetString("TABLE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team Members.
        /// </summary>
        public static string TEAM_MEMBERS {
            get {
                return ResourceManager.GetString("TEAM_MEMBERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical.
        /// </summary>
        public static string TECHNICAL {
            get {
                return ResourceManager.GetString("TECHNICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testimonial.
        /// </summary>
        public static string TESTIMONIAL {
            get {
                return ResourceManager.GetString("TESTIMONIAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your order!.
        /// </summary>
        public static string THANK_YOU_ORDER {
            get {
                return ResourceManager.GetString("THANK_YOU_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        public static string THREE {
            get {
                return ResourceManager.GetString("THREE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price.
        /// </summary>
        public static string TOTAL_PRICE {
            get {
                return ResourceManager.GetString("TOTAL_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        public static string TWO {
            get {
                return ResourceManager.GetString("TWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email..
        /// </summary>
        public static string VALIDATION_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("VALIDATION_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number..
        /// </summary>
        public static string VALIDATION_INVALID_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("VALIDATION_INVALID_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum allowed number of characters is {1}..
        /// </summary>
        public static string VALIDATION_MAX_CHARS {
            get {
                return ResourceManager.GetString("VALIDATION_MAX_CHARS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value must be between {1} and {2}..
        /// </summary>
        public static string VALIDATION_RANGE {
            get {
                return ResourceManager.GetString("VALIDATION_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid address..
        /// </summary>
        public static string VALIDATION_RANGE_ADDRESS {
            get {
                return ResourceManager.GetString("VALIDATION_RANGE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to have at least {1} but not more than {2} products in your cart..
        /// </summary>
        public static string VALIDATION_RANGE_CART_ITEM_QUANTITY {
            get {
                return ResourceManager.GetString("VALIDATION_RANGE_CART_ITEM_QUANTITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our tables currently fit between {1} and {2} people..
        /// </summary>
        public static string VALIDATION_RANGE_NUMBER_OF_PEOPLE {
            get {
                return ResourceManager.GetString("VALIDATION_RANGE_NUMBER_OF_PEOPLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reservation start time must be between {1} and {2}..
        /// </summary>
        public static string VALIDATION_RANGE_RESERVATION_TIME {
            get {
                return ResourceManager.GetString("VALIDATION_RANGE_RESERVATION_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide some more information - flat, floor number, etc..
        /// </summary>
        public static string VALIDATION_REQUIRED_ADDRESS_LINE_TWO {
            get {
                return ResourceManager.GetString("VALIDATION_REQUIRED_ADDRESS_LINE_TWO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a date..
        /// </summary>
        public static string VALIDATION_REQUIRED_DATE {
            get {
                return ResourceManager.GetString("VALIDATION_REQUIRED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In this field you can explain in detail..
        /// </summary>
        public static string VALIDATION_REQUIRED_DESCRIPTION {
            get {
                return ResourceManager.GetString("VALIDATION_REQUIRED_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your email..
        /// </summary>
        public static string VALIDATION_REQUIRED_EMAIL {
            get {
                return ResourceManager.GetString("VALIDATION_REQUIRED_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field is required..
        /// </summary>
        public static string VALIDATION_REQUIRED_FIELD {
            get {
                return ResourceManager.GetString("VALIDATION_REQUIRED_FIELD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your name..
        /// </summary>
        public static string VALIDATION_REQUIRED_NAME {
            get {
                return ResourceManager.GetString("VALIDATION_REQUIRED_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in your phone number..
        /// </summary>
        public static string VALIDATION_REQUIRED_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("VALIDATION_REQUIRED_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a rating..
        /// </summary>
        public static string VALIDATION_REQUIRED_RATING {
            get {
                return ResourceManager.GetString("VALIDATION_REQUIRED_RATING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a short summary..
        /// </summary>
        public static string VALIDATION_REQUIRED_SUMMARY {
            get {
                return ResourceManager.GetString("VALIDATION_REQUIRED_SUMMARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use cookies to understand how you use our site and to improve your experience..
        /// </summary>
        public static string WE_USE_COOKIES {
            get {
                return ResourceManager.GetString("WE_USE_COOKIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to.
        /// </summary>
        public static string WELCOME_TO {
            get {
                return ResourceManager.GetString("WELCOME_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working hours.
        /// </summary>
        public static string WORKING_HOURS {
            get {
                return ResourceManager.GetString("WORKING_HOURS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of.
        /// </summary>
        public static string YEARS_OF {
            get {
                return ResourceManager.GetString("YEARS_OF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can choose from our.
        /// </summary>
        public static string YOU_CAN_CHOOSE {
            get {
                return ResourceManager.GetString("YOU_CAN_CHOOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to.
        /// </summary>
        public static string YOU_NEED_TO {
            get {
                return ResourceManager.GetString("YOU_NEED_TO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your addresses.
        /// </summary>
        public static string YOUR_ADDRESSES {
            get {
                return ResourceManager.GetString("YOUR_ADDRESSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your name.
        /// </summary>
        public static string YOUR_NAME {
            get {
                return ResourceManager.GetString("YOUR_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your order.
        /// </summary>
        public static string YOUR_ORDER {
            get {
                return ResourceManager.GetString("YOUR_ORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your orders.
        /// </summary>
        public static string YOUR_ORDERS {
            get {
                return ResourceManager.GetString("YOUR_ORDERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your reservation.
        /// </summary>
        public static string YOUR_RESERVATION {
            get {
                return ResourceManager.GetString("YOUR_RESERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string ZIP {
            get {
                return ResourceManager.GetString("ZIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Reviews.
        /// </summary>
        public static string АLL_REVIEWS {
            get {
                return ResourceManager.GetString("АLL_REVIEWS", resourceCulture);
            }
        }
    }
}
